---
site_name: pypi-profile
site_url: https://github.com/matthewdeanmartin/matthewdeanmartin_pypi/tree/main/pypi_profile
site_author: Matthew Martin
site_description: CLI and FastAPI app for publishing PyPI maintainer profiles
repo_url: https://github.com/matthewdeanmartin/matthewdeanmartin_pypi
theme:
  name: readthedocs
  features: [navigation.footer]
edit_uri: edit/main/pypi_profile/docs/
markdown_extensions:
  - attr_list
  - codehilite
  - toc:
      permalink: true
nav:
  - Overview: overview/README.md
  - Installation: installation.md
  - Usage:
      - Quick start: usage/quickstart.md
  - Security: security.md
  - Contributing: extending/CONTRIBUTING.md
validation:
  nav:
    omitted_files: warn
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
