[tox]
min_version = 4.0
env_list = py310, py311, py312, py313, py314
;, py315 ; pydantic

requires =
    tox-uv>=1.28

[testenv]
dependency_groups = dev
commands =
    pytest {posargs:tests}
    ; mypy pypi_profile tests
