"""Metadata for john_doe. Generated by metametameta — do not edit by hand."""

__all__ = [
    "__title__",
    "__version__",
    "__description__",
    "__readme__",
    "__credits__",
    "__keywords__",
    "__license__",
    "__requires_python__",
    "__status__",
]

__title__ = "john-doe"
__version__ = "0.1.0"
__description__ = "Example pypi-profile plugin — proves two plugins can coexist."
__readme__ = "README.md"
__credits__ = [{"name": "Matthew Martin", "email": "matthewdeanmartin@gmail.com"}]
__keywords__ = ["pypi", "profile", "plugin"]
__license__ = "MIT"
__requires_python__ = ">=3.9"
__status__ = "3 - Alpha"
